version: "3.3"


services:
  tree-app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true        # for beautiful debug and pretty error output 
    stdin_open: true 
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVER_ADDR=http://localhost:3333
    ports:
      - 3000:3000
  
  web-server:
    image: nginx:alpine
    container_name: web-server
    ports:
      - 80:80
      - 443:443
    restart: always
    links:
      - tree-app
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf


