version: "3.3"

services:
  tree-app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true        # for beautiful debug and pretty error output 
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVER_ADDR=http://localhost:3333
    ports:
      - 3000:3000
  
  web-server:
    image: bitnami/nginx:1.12.0-r0
    container_name: web-server
    ports:
      - 8080:3000
      - 8443:3000
    restart: always
    links:
      - tree-app